version: 38
jobs:
- name: sync
  steps:
  - !PullRepository
    name: Pull from Remote
    remoteUrl: https://github.com/khose-ie/idms-onedev.git
    userName: khose-ie
    passwordSecret: GITHUB_TOKEN
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
