services:

    onedev-server:
        build:
            context: .
            dockerfile: dockerfile.onedev-server
        image: onedev-server:latest
        container_name: idms-onedev-server
        restart: unless-stopped
        environment:
            - POSTGRES_DB=onedev
            - POSTGRES_USER=onedev
            - POSTGRES_PASSWORD=onedev
        volumes:
            - onedev-server:/opt/onedev
            - onedev-backup:/root/backup
        ports:
            - 6610:6610
        depends_on:
            - onedev-database
        networks:
            - onedev

    onedev-database:
        image: postgres:17.3-alpine
        container_name: idms-onedev-database
        restart: unless-stopped
        environment:
            - POSTGRES_DB=onedev
            - POSTGRES_USER=onedev
            - POSTGRES_PASSWORD=onedev
        volumes:
            - onedev-database:/var/lib/postgresql/data
        networks:
            - onedev

    onedev-agent:
        build:
            context: .
            dockerfile: dockerfile.onedev-agent
        image: onedev-agent:latest
        container_name: idms-onedev-agent
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - serverUrl=http://onedev-server:6610
            - agentToken=a8c5f208-882b-4a9f-b96a-262d8e569530
        profiles:
            - agent
        networks:
            - onedev

networks:
    onedev:
        name: idms-onedev

volumes:
    onedev-server:
        name: idms-onedev-server

    onedev-database:
        name: idms-onedev-database

    onedev-backup:
        name: idms-onedev-backup
